---

plugins:
  - babel
  - jest
  - functional
  - testing-library
  - jest-dom


env:
  node: true
  jest: true
  browser: true
  es2020: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - "plugin:jest-dom/recommended"
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'

parserOptions:
  ecmaVersion: 2020

rules:
  import/extensions: 0
  import/no-unresolved: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-console: 0
  no-param-reassign: 0
