---

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  no-param-reassign: 0
